name: Playwright Test on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-playwright-test:
    name: Run Playwright Test
    timeout-minutes: 60
    runs-on: self-hosted

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      #  REMOVED this step, as it is unnecessary and triggers re-download
      # - name: Use local Playwright browsers
      #   run: |
      #     export PLAYWRIGHT_BROWSERS_PATH=0
      #     npx playwright install

      - name: Run Playwright Test
        run: npm run test
